# -*- coding: utf-8 -*-
"""home_work_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10w2TydnIEtWvoBgGhhonFJTaHON458D9
"""

# задаем переменные
correct_count = 0
scores = 0
percent = 0

# ввод имени пользователя и вывод приветствия
print("""Привет! Предлагаю проверить свои знания английского!
Напиши, как тебя зовут.""")
user_name = input()
print(f"Привет, {user_name}, начинаем тренировку!")

# вопросы и проверка ответов
print("Вопрос 1: \n My name ___ Vova.")
question_1 = input()
if question_1 == "is":
    print("Ответ верный! \nВы получаете 10 баллов!")
    correct_count += 1
else:
    print("Неправильно. \nВерный ответ: is")

print("Вопрос 2: \n I ___ a coder.")
question_2 = input()
if question_2 == "am":
    print("Ответ верный! \nВы получаете 10 баллов!")
    correct_count += 1
else:
    print("Неправильно. \nВерный ответ: am")

print("Вопрос 3: \n I live ___ Moscow.")
question_3 = input()
if question_3 == "in":
    print("Ответ верный! \nВы получаете 10 баллов!")
    correct_count += 1
else:
    print("Неправильно. \nВерный ответ: in")
print()

# подсчитываем итоги и выводим результат
scores = correct_count * 10
percent = round((correct_count / 3 * 100), 2)

print(f"""Вот и всё, {user_name}!
Вы ответили на {correct_count} вопросов из 3 верно.")

Вы заработали {scores} баллов.
Это {percent} процентов.""" )